### ISSUE TITLE
Js functies onderwater zetten wanneer js uit staat?

### ISSUE THREAD

**Issue by Davidvboxt** [iBadr49/visual-thinking#28]
Je kan misschien javascript functies zoals de pijltjes bij de carrousel weghalen of disable maken zodra javascript uit is. Dit zorgt ervoor dat de bezoeker weet dat hij die javascript functies niet kan gebruiken.

**Comment by iBadr49** [comment]
Dankjewel voor je feedback! deze is nu aangepast ..
