### ISSUE TITLE
2 sections (1 voor mobile en 1 voor desktop)

### ISSUE THREAD

**Issue by RayanSp** [iBadr49/visual-thinking#29]
Voor mobile en desktop is er een aparte section aangemaakt, dit is onnodig veel code. Bouw mobile first en gebruik media-queries om te werken naar desktop. 

https://github.com/iBadr49/visual-thinking/blob/11dae83d24129c9bc656b3f5592de4b4f4e74b23/src/lib/organisms/tekenmethodes.svelte#L60

**Comment by iBadr49** [comment]
ik heb nu de pagina ge refactored, probleem opgelost .. dankjewel voor  de feedback
