### ISSUE TITLE
Code en design review

### ISSUE THREAD

**Issue by zenitba** [iBadr49/visual-thinking#31]
**Tips**

- Leuk bij stappenplan die uitklap velden misschien handig als je een andere veld wilt uitklappen dat de vorige dicht gaat.
**Hier is een voorbeeld**
>https://codepen.io/krijnhoetmer/pen/JjzWXXB]

- Voor performance ik zie nergens dat je width en height gebruikt of lazy loading je ziet door de hele website wel dat de website shift.
**Artikel dat je kan helpen**
>https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/

**Tops**

- Mooi je werk gepresenteerd
- Je schetsen zien er goed passen ook bij de huisstijl.
- Heel leuk je toevoeging bij methode van de stappenplan en de carousel.

**Comment by iBadr49** [comment]
Dankjewel voor je feedback
